// Land cycle data for the MTG Monte Carlo Simulator.
// Imported as LANDS_JSON; App.jsx builds the LAND_DATA Map from LANDS_DATA.cycles[].
// Use JS module format (vs. JSON) to allow inline comments.
//
// Cycle structure:
//   name           – display name of the land cycle
//   behavior       – ETB/logic properties (descriptive, not read directly by the sim)
//   sim_flags      – boolean flags consumed by processLand() (see LAND_DATA builder in App.jsx)
//   mana_abilities – documentation only; not parsed by the simulator
//   lands[]        – individual land entries; per-land sim_flags override cycle-level flags

const LANDS_DATA = {
  database_name: 'MTG_Commander_Land_Cycles',
  version: '18.02.2026',
  format_support: 'Commander/EDH',
  cycles: [
    {
      name: 'Original Duals (ABUR)',
      behavior: { etb_tapped: false, has_basic_types: true, searchable: true },
      sim_flags: { entersTappedAlways: false },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Tundra', color_identity: ['W', 'U'], types: ['Plains', 'Island'] },
        { name: 'Underground Sea', color_identity: ['U', 'B'], types: ['Island', 'Swamp'] },
        { name: 'Badlands', color_identity: ['B', 'R'], types: ['Swamp', 'Mountain'] },
        { name: 'Taiga', color_identity: ['R', 'G'], types: ['Mountain', 'Forest'] },
        { name: 'Savannah', color_identity: ['G', 'W'], types: ['Forest', 'Plains'] },
        { name: 'Scrubland', color_identity: ['W', 'B'], types: ['Plains', 'Swamp'] },
        { name: 'Volcanic Island', color_identity: ['U', 'R'], types: ['Island', 'Mountain'] },
        { name: 'Bayou', color_identity: ['B', 'G'], types: ['Swamp', 'Forest'] },
        { name: 'Plateau', color_identity: ['R', 'W'], types: ['Mountain', 'Plains'] },
        { name: 'Tropical Island', color_identity: ['G', 'U'], types: ['Forest', 'Island'] },
      ],
    },
    {
      name: 'Shock Lands',
      behavior: {
        etb_tapped: true,
        untap_condition: 'pay_life',
        untap_cost: { life: 2 },
        has_basic_types: true,
        searchable: true,
      },
      sim_flags: { isShockLand: true, entersTappedAlways: false, lifeloss: 2 },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Hallowed Fountain', color_identity: ['W', 'U'], types: ['Plains', 'Island'] },
        { name: 'Watery Grave', color_identity: ['U', 'B'], types: ['Island', 'Swamp'] },
        { name: 'Blood Crypt', color_identity: ['B', 'R'], types: ['Swamp', 'Mountain'] },
        { name: 'Stomping Ground', color_identity: ['R', 'G'], types: ['Mountain', 'Forest'] },
        { name: 'Temple Garden', color_identity: ['G', 'W'], types: ['Forest', 'Plains'] },
        { name: 'Godless Shrine', color_identity: ['W', 'B'], types: ['Plains', 'Swamp'] },
        { name: 'Steam Vents', color_identity: ['U', 'R'], types: ['Island', 'Mountain'] },
        { name: 'Overgrown Tomb', color_identity: ['B', 'G'], types: ['Swamp', 'Forest'] },
        { name: 'Sacred Foundry', color_identity: ['R', 'W'], types: ['Mountain', 'Plains'] },
        { name: 'Breeding Pool', color_identity: ['G', 'U'], types: ['Forest', 'Island'] },
      ],
    },
    {
      name: 'Filter Lands',
      behavior: { etb_tapped: false, logic: 'filter_mana' },
      sim_flags: { isFilterLand: true, entersTappedAlways: false },
      mana_abilities: [
        { mode: 1, cost: '{T}', produces: '{C}' },
        { mode: 2, cost: '{A} or {B}, {T}', produces: 'Choice of {A}{A}, {A}{B}, or {B}{B}' },
      ],
      lands: [
        { name: 'Mystic Gate', color_identity: ['W', 'U'] },
        { name: 'Sunken Ruins', color_identity: ['U', 'B'] },
        { name: 'Graven Cairns', color_identity: ['B', 'R'] },
        { name: 'Fire-Lit Thicket', color_identity: ['R', 'G'] },
        { name: 'Wooded Bastion', color_identity: ['G', 'W'] },
        { name: 'Fetid Heath', color_identity: ['W', 'B'] },
        { name: 'Cascade Bluffs', color_identity: ['U', 'R'] },
        { name: 'Twilight Mire', color_identity: ['B', 'G'] },
        { name: 'Rugged Prairie', color_identity: ['R', 'W'] },
        { name: 'Flooded Grove', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Triomes',
      behavior: { etb_tapped: true, has_basic_types: true, searchable: true, cycling: true },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A], [Color B], or [Color C]' }],
      lands: [
        {
          name: 'Savai Triome',
          color_identity: ['R', 'W', 'B'],
          types: ['Mountain', 'Plains', 'Swamp'],
        },
        {
          name: 'Ketria Triome',
          color_identity: ['G', 'U', 'R'],
          types: ['Forest', 'Island', 'Mountain'],
        },
        {
          name: 'Indatha Triome',
          color_identity: ['W', 'B', 'G'],
          types: ['Plains', 'Swamp', 'Forest'],
        },
        {
          name: 'Raugrin Triome',
          color_identity: ['U', 'R', 'W'],
          types: ['Island', 'Mountain', 'Plains'],
        },
        {
          name: 'Zagoth Triome',
          color_identity: ['B', 'G', 'U'],
          types: ['Swamp', 'Forest', 'Island'],
        },
        {
          name: "Jetmir's Garden",
          color_identity: ['R', 'G', 'W'],
          types: ['Mountain', 'Forest', 'Plains'],
        },
        {
          name: "Raffine's Tower",
          color_identity: ['W', 'U', 'B'],
          types: ['Plains', 'Island', 'Swamp'],
        },
        {
          name: "Spara's Headquarters",
          color_identity: ['G', 'W', 'U'],
          types: ['Forest', 'Plains', 'Island'],
        },
        {
          name: "Xander's Lounge",
          color_identity: ['U', 'B', 'R'],
          types: ['Island', 'Swamp', 'Mountain'],
        },
        {
          name: "Ziatora's Proving Ground",
          color_identity: ['B', 'R', 'G'],
          types: ['Swamp', 'Mountain', 'Forest'],
        },
      ],
    },
    {
      name: 'Battle Lands (Tango Lands)',
      behavior: {
        etb_tapped: true,
        untap_condition: 'control_2_plus_basics',
        has_basic_types: true,
        searchable: true,
      },
      sim_flags: { isBattleLand: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Prairie Stream', color_identity: ['W', 'U'], types: ['Plains', 'Island'] },
        { name: 'Sunken Hollow', color_identity: ['U', 'B'], types: ['Island', 'Swamp'] },
        { name: 'Smoldering Marsh', color_identity: ['B', 'R'], types: ['Swamp', 'Mountain'] },
        { name: 'Cinder Glade', color_identity: ['R', 'G'], types: ['Mountain', 'Forest'] },
        { name: 'Canopy Vista', color_identity: ['G', 'W'], types: ['Forest', 'Plains'] },
        { name: 'Radiant Summit', color_identity: ['R', 'W'], types: ['Mountain', 'Plains'] },
        { name: 'Vernal Fen', color_identity: ['B', 'G'], types: ['Swamp', 'Forest'] },
        { name: 'Sodden Verdure', color_identity: ['G', 'U'], types: ['Forest', 'Island'] },
      ],
    },
    {
      name: 'Surveil Lands (MKM)',
      behavior: {
        etb_tapped: true,
        etb_trigger: 'surveil_1',
        has_basic_types: true,
        searchable: true,
      },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Meticulous Archive', color_identity: ['W', 'U'], types: ['Plains', 'Island'] },
        { name: 'Undercity Sewers', color_identity: ['U', 'B'], types: ['Island', 'Swamp'] },
        { name: 'Raucous Theater', color_identity: ['B', 'R'], types: ['Swamp', 'Mountain'] },
        { name: 'Commercial District', color_identity: ['R', 'G'], types: ['Mountain', 'Forest'] },
        { name: 'Lush Portico', color_identity: ['G', 'W'], types: ['Forest', 'Plains'] },
        { name: 'Shadowy Backstreet', color_identity: ['W', 'B'], types: ['Plains', 'Swamp'] },
        { name: 'Thundering Falls', color_identity: ['U', 'R'], types: ['Island', 'Mountain'] },
        { name: 'Underground Mortuary', color_identity: ['B', 'G'], types: ['Swamp', 'Forest'] },
        { name: 'Elegant Parlor', color_identity: ['R', 'W'], types: ['Mountain', 'Plains'] },
        { name: 'Hedge Maze', color_identity: ['G', 'U'], types: ['Forest', 'Island'] },
      ],
    },
    {
      name: 'Reveal Lands (Show Lands / Snarls)',
      behavior: {
        etb_tapped: true,
        untap_condition: 'reveal_land_type_from_hand',
        has_basic_types: false,
      },
      sim_flags: { isReveal: true, entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Port Town', color_identity: ['W', 'U'], reveals: ['Plains', 'Island'] },
        { name: 'Choked Estuary', color_identity: ['U', 'B'], reveals: ['Island', 'Swamp'] },
        { name: 'Foreboding Ruins', color_identity: ['B', 'R'], reveals: ['Swamp', 'Mountain'] },
        { name: 'Game Trail', color_identity: ['R', 'G'], reveals: ['Mountain', 'Forest'] },
        { name: 'Fortified Village', color_identity: ['G', 'W'], reveals: ['Forest', 'Plains'] },
        { name: 'Shineshadow Snarl', color_identity: ['W', 'B'], reveals: ['Plains', 'Swamp'] },
        { name: 'Frostboil Snarl', color_identity: ['U', 'R'], reveals: ['Island', 'Mountain'] },
        { name: 'Necroblossom Snarl', color_identity: ['B', 'G'], reveals: ['Swamp', 'Forest'] },
        { name: 'Furycalm Snarl', color_identity: ['R', 'W'], reveals: ['Mountain', 'Plains'] },
        { name: 'Vineglimmer Snarl', color_identity: ['G', 'U'], reveals: ['Forest', 'Island'] },
      ],
    },
    {
      name: 'Hideaway Lands',
      behavior: { etb_tapped: true, keyword: 'Hideaway 4', has_basic_types: false },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [
        { mode: 1, cost: '{T}', produces: '[Color A]' },
        {
          mode: 2,
          cost: '{A}, {T}',
          produces: 'Cast exiled card without paying mana cost',
          condition: 'specific_game_state_met',
        },
      ],
      lands: [
        { name: 'Windbrisk Heights', color_identity: ['W'], condition: 'attack_with_3_creatures' },
        { name: 'Shelldock Isle', color_identity: ['U'], condition: 'library_size_le_20' },
        { name: 'Howltooth Hollow', color_identity: ['B'], condition: 'all_players_hand_size_0' },
        { name: 'Spinerock Knoll', color_identity: ['R'], condition: 'opponent_dealt_7_damage' },
        { name: 'Mosswort Bridge', color_identity: ['G'], condition: 'total_power_ge_10' },
      ],
    },
    {
      name: 'Pain Lands',
      behavior: { etb_tapped: false, logic: 'choice_damage_or_colorless' },
      sim_flags: { isPainLand: true, entersTappedAlways: false, lifeloss: 1 },
      mana_abilities: [
        { mode: 1, cost: '{T}', produces: '{C}' },
        { mode: 2, cost: '{T}, Pay 1 Life', produces: 'Choice of [Color A] or [Color B]' },
      ],
      lands: [
        { name: 'Adarkar Wastes', color_identity: ['W', 'U'] },
        { name: 'Underground River', color_identity: ['U', 'B'] },
        { name: 'Sulfurous Springs', color_identity: ['B', 'R'] },
        { name: 'Karplusan Forest', color_identity: ['R', 'G'] },
        { name: 'Brushland', color_identity: ['G', 'W'] },
        { name: 'Caves of Koilos', color_identity: ['W', 'B'] },
        { name: 'Shivan Reef', color_identity: ['U', 'R'] },
        { name: 'Llanowar Wastes', color_identity: ['B', 'G'] },
        { name: 'Battlefield Forge', color_identity: ['R', 'W'] },
        { name: 'Yavimaya Coast', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Check Lands',
      behavior: { etb_tapped: true, untap_condition: 'control_basic_land_type_of_colors' },
      sim_flags: { isCheck: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Glacial Fortress', color_identity: ['W', 'U'], checks: ['Plains', 'Island'] },
        { name: 'Drowned Catacomb', color_identity: ['U', 'B'], checks: ['Island', 'Swamp'] },
        { name: 'Dragonskull Summit', color_identity: ['B', 'R'], checks: ['Swamp', 'Mountain'] },
        { name: 'Rootbound Crag', color_identity: ['R', 'G'], checks: ['Mountain', 'Forest'] },
        { name: 'Sunpetal Grove', color_identity: ['G', 'W'], checks: ['Forest', 'Plains'] },
        { name: 'Isolated Chapel', color_identity: ['W', 'B'], checks: ['Plains', 'Swamp'] },
        { name: 'Sulfur Falls', color_identity: ['U', 'R'], checks: ['Island', 'Mountain'] },
        { name: 'Woodland Cemetery', color_identity: ['B', 'G'], checks: ['Swamp', 'Forest'] },
        { name: 'Clifftop Retreat', color_identity: ['R', 'W'], checks: ['Mountain', 'Plains'] },
        { name: 'Hinterland Harbor', color_identity: ['G', 'U'], checks: ['Forest', 'Island'] },
      ],
    },
    {
      name: 'Bond Lands (Crowd Lands)',
      behavior: {
        etb_tapped: true,
        untap_condition: 'opponent_count_ge_2',
        has_basic_types: false,
      },
      sim_flags: { isCrowd: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Sea of Clouds', color_identity: ['W', 'U'] },
        { name: 'Morphic Pool', color_identity: ['U', 'B'] },
        { name: 'Luxury Suite', color_identity: ['B', 'R'] },
        { name: 'Spire Garden', color_identity: ['R', 'G'] },
        { name: 'Bountiful Promenade', color_identity: ['G', 'W'] },
        { name: 'Vault of Champions', color_identity: ['W', 'B'] },
        { name: 'Training Center', color_identity: ['U', 'R'] },
        { name: 'Undergrowth Stadium', color_identity: ['B', 'G'] },
        { name: 'Spectator Seating', color_identity: ['R', 'W'] },
        { name: 'Rejuvenating Springs', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Slow Lands',
      behavior: { etb_tapped: true, untap_condition: 'control_lands_ge_2', has_basic_types: false },
      sim_flags: { isSlowLand: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Deserted Beach', color_identity: ['W', 'U'] },
        { name: 'Shipwreck Marsh', color_identity: ['U', 'B'] },
        { name: 'Haunted Ridge', color_identity: ['B', 'R'] },
        { name: 'Rockfall Vale', color_identity: ['R', 'G'] },
        { name: 'Overgrown Farmland', color_identity: ['G', 'W'] },
        { name: 'Shattered Sanctum', color_identity: ['W', 'B'] },
        { name: 'Stormcarved Coast', color_identity: ['U', 'R'] },
        { name: 'Deathcap Glade', color_identity: ['B', 'G'] },
        { name: 'Sundown Pass', color_identity: ['R', 'W'] },
        { name: 'Dreamroot Cascade', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Fast Lands',
      behavior: { etb_tapped: true, untap_condition: 'control_lands_le_2', has_basic_types: false },
      sim_flags: { isFast: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Seachrome Coast', color_identity: ['W', 'U'] },
        { name: 'Darkslick Shores', color_identity: ['U', 'B'] },
        { name: 'Blackcleave Cliffs', color_identity: ['B', 'R'] },
        { name: 'Copperline Gorge', color_identity: ['R', 'G'] },
        { name: 'Razorverge Thicket', color_identity: ['G', 'W'] },
        { name: 'Concealed Courtyard', color_identity: ['W', 'B'] },
        { name: 'Spirebluff Canal', color_identity: ['U', 'R'] },
        { name: 'Blooming Marsh', color_identity: ['B', 'G'] },
        { name: 'Inspiring Vantage', color_identity: ['R', 'W'] },
        { name: 'Botanical Sanctum', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Lair Lands',
      behavior: { etb_tapped: false, logic: 'bounce_non_lair_on_etb' },
      sim_flags: { isBounce: true, entersTappedAlways: false },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A], [Color B], or [Color C]' }],
      lands: [
        { name: "Dromar's Cavern", color_identity: ['W', 'U', 'B'] },
        { name: "Crosis's Catacombs", color_identity: ['U', 'B', 'R'] },
        { name: "Darigaaz's Caldera", color_identity: ['B', 'R', 'G'] },
        { name: "Rith's Grove", color_identity: ['R', 'G', 'W'] },
        { name: "Treva's Ruins", color_identity: ['G', 'W', 'U'] },
      ],
    },
    {
      name: 'Bounce Lands (Karoos)',
      behavior: { etb_tapped: true, logic: 'return_land_on_etb' },
      sim_flags: { isBounce: true, entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: '{A}{B}' }],
      lands: [
        { name: 'Azorius Chancery', color_identity: ['W', 'U'] },
        { name: 'Dimir Aqueduct', color_identity: ['U', 'B'] },
        { name: 'Rakdos Carnarium', color_identity: ['B', 'R'] },
        { name: 'Gruul Turf', color_identity: ['R', 'G'] },
        { name: 'Selesnya Sanctuary', color_identity: ['G', 'W'] },
        { name: 'Orzhov Basilica', color_identity: ['W', 'B'] },
        { name: 'Izzet Boilerworks', color_identity: ['U', 'R'] },
        { name: 'Golgari Rot Farm', color_identity: ['B', 'G'] },
        { name: 'Boros Garrison', color_identity: ['R', 'W'] },
        { name: 'Simic Growth Chamber', color_identity: ['G', 'U'] },
        {
          name: 'Guildless Commons',
          color_identity: ['C'],
          mana_abilities: [{ cost: '{T}', produces: '{C}{C}' }],
        },
      ],
    },
    {
      name: 'Gate Cycle',
      behavior: { etb_tapped: true, subtype: 'Gate' },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Azorius Guildgate', color_identity: ['W', 'U'] },
        { name: 'Dimir Guildgate', color_identity: ['U', 'B'] },
        { name: 'Rakdos Guildgate', color_identity: ['B', 'R'] },
        { name: 'Gruul Guildgate', color_identity: ['R', 'G'] },
        { name: 'Selesnya Guildgate', color_identity: ['G', 'W'] },
        { name: 'Orzhov Guildgate', color_identity: ['W', 'B'] },
        { name: 'Izzet Guildgate', color_identity: ['U', 'R'] },
        { name: 'Golgari Guildgate', color_identity: ['B', 'G'] },
        { name: 'Boros Guildgate', color_identity: ['R', 'W'] },
        { name: 'Simic Guildgate', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Tri-Lands (Shard/Wedge)',
      behavior: { etb_tapped: true },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A], [Color B], or [Color C]' }],
      lands: [
        { name: 'Mystic Monastery', color_identity: ['U', 'R', 'W'] },
        { name: 'Opulent Palace', color_identity: ['B', 'G', 'U'] },
        { name: 'Nomad Outpost', color_identity: ['R', 'W', 'B'] },
        { name: 'Frontier Bivouac', color_identity: ['G', 'U', 'R'] },
        { name: 'Sandsteppe Citadel', color_identity: ['W', 'B', 'G'] },
        { name: 'Seaside Citadel', color_identity: ['G', 'W', 'U'] },
        { name: 'Arcane Sanctum', color_identity: ['W', 'U', 'B'] },
        { name: 'Crumbling Necropolis', color_identity: ['U', 'B', 'R'] },
        { name: 'Savage Lands', color_identity: ['B', 'R', 'G'] },
        { name: 'Jungle Shrine', color_identity: ['R', 'G', 'W'] },
      ],
    },
    {
      name: 'Scry Lands',
      behavior: { etb_tapped: true, etb_trigger: 'scry_1' },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Temple of Enlightenment', color_identity: ['W', 'U'] },
        { name: 'Temple of Deceit', color_identity: ['U', 'B'] },
        { name: 'Temple of Malice', color_identity: ['B', 'R'] },
        { name: 'Temple of Abandon', color_identity: ['R', 'G'] },
        { name: 'Temple of Plenty', color_identity: ['G', 'W'] },
        { name: 'Temple of Silence', color_identity: ['W', 'B'] },
        { name: 'Temple of Epiphany', color_identity: ['U', 'R'] },
        { name: 'Temple of Malady', color_identity: ['B', 'G'] },
        { name: 'Temple of Triumph', color_identity: ['R', 'W'] },
        { name: 'Temple of Mystery', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Vivid Lands',
      behavior: { etb_tapped: true, logic: 'charge_counters' },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [
        { mode: 1, cost: '{T}', produces: '[Primary Color]' },
        { mode: 2, cost: '{T}, Remove charge counter', produces: 'Any Color' },
      ],
      lands: [
        { name: 'Vivid Meadow', color_identity: ['W'] },
        { name: 'Vivid Creek', color_identity: ['U'] },
        { name: 'Vivid Marsh', color_identity: ['B'] },
        { name: 'Vivid Crag', color_identity: ['R'] },
        { name: 'Vivid Grove', color_identity: ['G'] },
      ],
    },
    {
      name: 'Pathway Lands',
      behavior: { is_modal: true, etb_tapped: false, logic: 'choose_side_on_play' },
      sim_flags: { isPathway: true, entersTappedAlways: false },
      mana_abilities: [{ cost: '{T}', produces: 'Color of chosen face' }],
      lands: [
        { name: 'Hengegate Pathway', color_identity: ['W', 'U'] },
        { name: 'Clearwater Pathway', color_identity: ['U', 'B'] },
        { name: 'Blightstep Pathway', color_identity: ['B', 'R'] },
        { name: 'Cragcrown Pathway', color_identity: ['R', 'G'] },
        { name: 'Branchloft Pathway', color_identity: ['G', 'W'] },
        { name: 'Brightclimb Pathway', color_identity: ['W', 'B'] },
        { name: 'Riverglide Pathway', color_identity: ['U', 'R'] },
        { name: 'Darkbore Pathway', color_identity: ['B', 'G'] },
        { name: 'Needleverge Pathway', color_identity: ['R', 'W'] },
        { name: 'Barkchannel Pathway', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Legendary Ramp Utility',
      behavior: { logic: 'scaling_mana' },
      sim_flags: { entersTappedAlways: false },
      lands: [
        {
          name: 'Nykthos, Shrine to Nyx',
          color_identity: ['C'],
          sim_flags: { scalesWithDevotion: true, manaFloor: 1, simplified: 'turn-1' },
          mana_abilities: [
            { mode: 1, cost: '{T}', produces: '{C}' },
            {
              mode: 2,
              cost: '{2}, {T}',
              produces: 'Amount equal to devotion to chosen color',
              simplified: 'turn-1',
            },
          ],
        },
        {
          name: 'Cabal Coffers',
          color_identity: ['B'],
          sim_flags: { scalesWithSwamps: true },
          mana_abilities: [
            { mode: 1, cost: '{2}, {T}', produces: '{B} for each Swamp you control' },
          ],
        },
        {
          name: 'Phyrexian Tower',
          color_identity: ['B'],
          sim_flags: { isPhyrexianTower: true },
          mana_abilities: [
            { mode: 1, cost: '{T}', produces: '{C}' },
            { mode: 2, cost: '{T}, Sacrifice a creature', produces: '{B}{B}' },
          ],
        },
        {
          name: 'Three Tree City',
          color_identity: ['C'],
          sim_flags: { scalesWithCreatureTypes: true, manaFloor: 1, simplified: 'turn-1' },
          mana_abilities: [
            { mode: 1, cost: '{T}', produces: '{C}' },
            {
              mode: 2,
              cost: '{2}, {T}',
              produces: 'Amount of [Color] equal to chosen creature type count',
              simplified: 'turn-1',
            },
          ],
        },
        {
          name: 'Temple of the False God',
          color_identity: ['C'],
          sim_flags: { isTempleOfFalseGod: true },
          mana_abilities: [
            { cost: '{T}', produces: '{C}{C}', condition: 'Control 5 or more lands' },
          ],
        },
        // ── Permanent-count Scalers (simplified as turn-1 mana in sim) ────────
        {
          name: "Gaea's Cradle",
          color_identity: ['G'],
          sim_flags: { scalesWithCreatures: true, manaFloor: 1, simplified: 'turn-1' },
          mana_abilities: [
            { cost: '{T}', produces: '{G} for each creature you control', simplified: 'turn-1' },
          ],
        },
        {
          name: "Serra's Sanctum",
          color_identity: ['W'],
          sim_flags: { scalesWithEnchantments: true, manaFloor: 1, simplified: 'turn-1' },
          mana_abilities: [
            { cost: '{T}', produces: '{W} for each enchantment you control', simplified: 'turn-1' },
          ],
        },
        {
          name: 'Tolarian Academy',
          color_identity: ['U'],
          sim_flags: { scalesWithArtifacts: true, manaFloor: 1, simplified: 'turn-1' },
          mana_abilities: [
            { cost: '{T}', produces: '{U} for each artifact you control', simplified: 'turn-1' },
          ],
        },
        // ── Swamp-count Scalers ({2},{T} activation, computable from battlefield) ─
        {
          name: 'Cabal Stronghold',
          color_identity: ['B'],
          sim_flags: { scalesWithBasicSwamps: true },
          mana_abilities: [{ cost: '{2}, {T}', produces: '{B} for each basic Swamp you control' }],
        },
        // ── Graveyard Scaler (simplified as turn-1 mana in sim) ───────────────
        {
          name: 'Crypt of Agadeem',
          color_identity: ['B'],
          sim_flags: { scalesWithGraveyard: true, manaFloor: 1, simplified: 'turn-1' },
          mana_abilities: [
            {
              cost: '{2}, {T}',
              produces: '{B} for each black creature card in graveyard',
              simplified: 'turn-1',
            },
          ],
        },
      ],
    },
    {
      name: 'Verge Lands (2024-2026)',
      behavior: {
        etb_tapped: false,
        logic: 'primary_always_secondary_requires_basic_type',
        has_basic_types: false,
      },
      sim_flags: { entersTappedAlways: false, isVerge: true },
      mana_abilities: [
        { mode: 1, cost: '{T}', produces: '[Primary Color]' },
        {
          mode: 2,
          cost: '{T}',
          produces: '[Secondary Color]',
          condition: 'Control land of secondary type',
        },
      ],
      lands: [
        {
          name: 'Sunbillow Verge',
          color_identity: ['W', 'R'],
          primary: 'W',
          secondary_check: 'Mountain',
        },
        {
          name: 'Gloomlake Verge',
          color_identity: ['U', 'B'],
          primary: 'U',
          secondary_check: 'Swamp',
        },
        {
          name: 'Blazemire Verge',
          color_identity: ['B', 'R'],
          primary: 'B',
          secondary_check: 'Mountain',
        },
        {
          name: 'Thornspire Verge',
          color_identity: ['R', 'G'],
          primary: 'R',
          secondary_check: 'Forest',
        },
        {
          name: 'Willowrush Verge',
          color_identity: ['G', 'W'],
          primary: 'G',
          secondary_check: 'Plains',
        },
        {
          name: 'Bleachbone Verge',
          color_identity: ['W', 'B'],
          primary: 'W',
          secondary_check: 'Swamp',
        },
        {
          name: 'Riverpyre Verge',
          color_identity: ['U', 'R'],
          primary: 'U',
          secondary_check: 'Mountain',
        },
        {
          name: 'Clutchvine Verge',
          color_identity: ['B', 'G'],
          primary: 'B',
          secondary_check: 'Forest',
        },
        {
          name: 'Cinderfall Verge',
          color_identity: ['R', 'W'],
          primary: 'R',
          secondary_check: 'Plains',
        },
        {
          name: 'Floodplain Verge',
          color_identity: ['G', 'U'],
          primary: 'G',
          secondary_check: 'Island',
        },
      ],
    },
    {
      name: 'Specific Utility & Rainbow',
      behavior: { logic: 'utility' },
      sim_flags: { entersTappedAlways: false, isUtilityUntapped: true },
      lands: [
        {
          name: 'Command Tower',
          color_identity: ['W', 'U', 'B', 'R', 'G'],
          sim_flags: { isUtilityUntapped: true },
          mana_abilities: [{ cost: '{T}', produces: "Any color in Commander's Identity" }],
        },
        {
          name: 'Mana Confluence',
          color_identity: ['W', 'U', 'B', 'R', 'G'],
          sim_flags: { isFiveColorPainLand: true, lifeloss: 1 },
          mana_abilities: [{ cost: '{T}, Pay 1 Life', produces: 'Any Color' }],
        },
        {
          name: 'City of Brass',
          color_identity: ['W', 'U', 'B', 'R', 'G'],
          sim_flags: { isFiveColorPainLand: true, lifeloss: 1 },
          mana_abilities: [{ cost: '{T}', produces: 'Any Color (Deal 1 damage)' }],
        },
        {
          name: 'Reflecting Pool',
          color_identity: ['W', 'U', 'B', 'R', 'G'],
          mana_abilities: [{ cost: '{T}', produces: 'Any color a land you control could produce' }],
        },
        {
          name: 'Exotic Orchard',
          color_identity: ['W', 'U', 'B', 'R', 'G'],
          mana_abilities: [{ cost: '{T}', produces: "Any color an opponent's land could produce" }],
        },
        {
          name: 'Forbidden Orchard',
          color_identity: ['W', 'U', 'B', 'R', 'G'],
          mana_abilities: [
            { cost: '{T}', produces: 'Any Color', effect: 'Target opponent creates 1/1 Spirit' },
          ],
        },
        {
          name: 'Gemstone Caverns',
          color_identity: ['C'],
          mana_abilities: [
            { cost: '{T}', produces: '{C}' },
            { cost: '{T}', produces: 'Any Color', condition: 'Has Luck Counter' },
          ],
        },
        {
          name: 'Cavern of Souls',
          color_identity: ['C'],
          mana_abilities: [
            { cost: '{T}', produces: '{C}' },
            { cost: '{T}', produces: 'Any Color (Creature Type Only, Uncounterable)' },
          ],
        },
        {
          name: 'Unclaimed Territory',
          color_identity: ['C'],
          mana_abilities: [
            { cost: '{T}', produces: '{C}' },
            { cost: '{T}', produces: 'Any Color (Creature Type Only)' },
          ],
        },
        {
          name: 'Secluded Courtyard',
          color_identity: ['C'],
          mana_abilities: [
            { cost: '{T}', produces: '{C}' },
            { cost: '{T}', produces: 'Any Color (Creature Type spell or ability)' },
          ],
        },
        {
          name: 'Starting Town',
          color_identity: ['W', 'U', 'B', 'R', 'G'],
          sim_flags: { lifeloss: 1 },
          behavior: { etb_tapped: 'conditional' },
          mana_abilities: [
            { cost: '{T}', produces: '{C}' },
            { cost: '{T}, Pay 1 Life', produces: 'Any Color' },
          ],
        },
        {
          name: 'Reliquary Tower',
          color_identity: ['C'],
          sim_flags: { isUtilityUntapped: true },
          mana_abilities: [{ cost: '{T}', produces: '{C}' }],
          passive: 'No maximum hand size',
        },
        {
          name: 'Tarnished Citadel',
          color_identity: ['C'],
          mana_abilities: [
            { cost: '{T}', produces: '{C}' },
            { cost: '{T}, Pay 3 Life', produces: 'Any Color' },
          ],
        },
      ],
    },
    {
      name: 'MDFCs & Modal Lands',
      behavior: {
        is_mdfc: true,
        face_logic: 'spell_front_land_back',
        etb_logic: 'pay_3_life_or_enter_tapped',
      },
      sim_flags: { isMDFCLand: true, entersTappedAlways: false, lifeloss: 3 },
      mana_abilities: [
        {
          cost: '{T}',
          produces: '[Single Color]',
          note: "As this land enters, you may pay 3 life. If you don't, it enters tapped.",
        },
      ],
      lands: [
        { name: 'Boggart Trawler', color_identity: ['B'] },
        { name: 'Bridgeworks Battle', color_identity: ['W'] },
        { name: 'Disciple of Freyalise', color_identity: ['G'] },
        { name: "Emeria's Call", color_identity: ['W'] },
        { name: 'Fell the Profane', color_identity: ['B'] },
        { name: 'Hydroelectric Specimen', color_identity: ['U'] },
        { name: 'Pinnacle Monk', color_identity: ['W'] },
        { name: 'Razorgrass Ambush', color_identity: ['G'] },
        { name: 'Sea Gate Restoration', color_identity: ['U'] },
        { name: 'Shatterskull Smashing', color_identity: ['R'] },
        { name: 'Sink into Stupor', color_identity: ['U'] },
        { name: 'Sundering Eruption', color_identity: ['R'] },
        { name: 'Turntimber Symbiosis', color_identity: ['G'] },
        { name: 'Witch Enchanter', color_identity: ['W'] },
      ],
    },
    {
      name: 'Tron Lands',
      behavior: { etb_tapped: false, logic: 'assemble_3_for_7_mana' },
      sim_flags: { entersTappedAlways: false },
      mana_abilities: [
        { cost: '{T}', produces: '{C}' },
        {
          cost: '{T}',
          produces: '{C}{C} or {C}{C}{C}',
          condition: 'Control Mine, Power Plant, and Tower',
        },
      ],
      lands: [
        { name: "Urza's Tower", color_identity: ['C'] },
        { name: "Urza's Mine", color_identity: ['C'] },
        { name: "Urza's Power Plant", color_identity: ['C'] },
      ],
    },
    {
      name: 'Bicycle Lands (Amonkhet)',
      behavior: { etb_tapped: true, cycling: true, has_basic_types: true, searchable: true },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Irrigated Farmland', color_identity: ['W', 'U'], types: ['Plains', 'Island'] },
        { name: 'Fetid Pools', color_identity: ['U', 'B'], types: ['Island', 'Swamp'] },
        { name: 'Canyon Slough', color_identity: ['B', 'R'], types: ['Swamp', 'Mountain'] },
        { name: 'Sheltered Thicket', color_identity: ['R', 'G'], types: ['Mountain', 'Forest'] },
        { name: 'Scattered Groves', color_identity: ['G', 'W'], types: ['Forest', 'Plains'] },
      ],
    },
    {
      name: 'Gain Lands (KTK / Core Set)',
      behavior: { etb_tapped: true, etb_trigger: 'gain_1_life' },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Tranquil Cove', color_identity: ['W', 'U'] },
        { name: 'Dismal Backwater', color_identity: ['U', 'B'] },
        { name: 'Bloodfell Caves', color_identity: ['B', 'R'] },
        { name: 'Rugged Highlands', color_identity: ['R', 'G'] },
        { name: 'Blossoming Sands', color_identity: ['G', 'W'] },
        { name: 'Scoured Barrens', color_identity: ['W', 'B'] },
        { name: 'Swiftwater Cliffs', color_identity: ['U', 'R'] },
        { name: 'Jungle Hollow', color_identity: ['B', 'G'] },
        { name: 'Wind-Scarred Crag', color_identity: ['R', 'W'] },
        { name: 'Thornwood Falls', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Refuge Lands (Zendikar)',
      behavior: { etb_tapped: true, etb_trigger: 'gain_1_life' },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Sejiri Refuge', color_identity: ['W', 'U'] },
        { name: 'Jwar Isle Refuge', color_identity: ['U', 'B'] },
        { name: 'Akoum Refuge', color_identity: ['B', 'R'] },
        { name: 'Kazandu Refuge', color_identity: ['R', 'G'] },
        { name: 'Graypelt Refuge', color_identity: ['G', 'W'] },
      ],
    },
    {
      name: 'Coastal Lands (Invasion)',
      behavior: { etb_tapped: true },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Coastal Tower', color_identity: ['W', 'U'] },
        { name: 'Salt Marsh', color_identity: ['U', 'B'] },
        { name: 'Urborg Volcano', color_identity: ['B', 'R'] },
        { name: 'Shivan Oasis', color_identity: ['R', 'G'] },
        { name: 'Elfhame Palace', color_identity: ['G', 'W'] },
      ],
    },
    {
      name: 'Depletion Lands (Mercadian Masques)',
      behavior: { etb_tapped: true, logic: 'depletion_counters' },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [
        { cost: '{T}, Remove depletion counter', produces: '[Color A] or [Color B]' },
      ],
      lands: [
        { name: 'Saprazzan Skerry', color_identity: ['W', 'U'] },
        { name: 'Remote Farm', color_identity: ['U', 'B'] },
        { name: 'Rushwood Grove', color_identity: ['R', 'G'] },
        { name: 'Sandstone Needle', color_identity: ['B', 'R'] },
        { name: 'Hickory Woodlot', color_identity: ['G', 'W'] },
        { name: 'Peat Bog', color_identity: ['B'] },
        { name: 'Timberline Ridge', color_identity: ['G'] },
        { name: 'Caldera Lake', color_identity: ['R'] },
        { name: 'Hollow Trees', color_identity: ['W'] },
      ],
    },
    {
      name: 'Thriving Lands (Commander Legends)',
      behavior: { etb_tapped: true, etb_trigger: 'choose_color_on_etb' },
      sim_flags: { entersTappedAlways: true, isThriving: true },
      mana_abilities: [{ cost: '{T}', produces: '[Primary Color] or chosen color' }],
      lands: [
        { name: 'Thriving Bluff', color_identity: ['R'] },
        { name: 'Thriving Grove', color_identity: ['G'] },
        { name: 'Thriving Heath', color_identity: ['W'] },
        { name: 'Thriving Isle', color_identity: ['U'] },
        { name: 'Thriving Moor', color_identity: ['B'] },
      ],
    },
    {
      name: 'Horizon Lands',
      behavior: { etb_tapped: false, logic: 'pay_1_life_for_color' },
      sim_flags: { isHorizonLand: true, entersTappedAlways: false, lifeloss: 1 },
      mana_abilities: [{ cost: '{T}, Pay 1 Life', produces: '[Color A] or [Color B]' }],
      lands: [
        { name: 'Horizon Canopy', color_identity: ['G', 'W'] },
        { name: 'Fiery Islet', color_identity: ['U', 'R'] },
        { name: 'Nurturing Peatland', color_identity: ['B', 'G'] },
        { name: 'Silent Clearing', color_identity: ['W', 'B'] },
        { name: 'Sunbaked Canyon', color_identity: ['R', 'W'] },
        { name: 'Waterlogged Grove', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Man Lands (Creature Lands)',
      behavior: { etb_tapped: true, logic: 'can_animate_as_creature' },
      sim_flags: { entersTappedAlways: true, isManLand: true },
      mana_abilities: [{ cost: '{T}', produces: 'Choice of [Color A] or [Color B]' }],
      lands: [
        { name: 'Celestial Colonnade', color_identity: ['W', 'U'] },
        { name: 'Creeping Tar Pit', color_identity: ['U', 'B'] },
        { name: 'Lavaclaw Reaches', color_identity: ['B', 'R'] },
        { name: 'Raging Ravine', color_identity: ['R', 'G'] },
        { name: 'Stirring Wildwood', color_identity: ['G', 'W'] },
        { name: 'Shambling Vent', color_identity: ['W', 'B'] },
        { name: 'Wandering Fumarole', color_identity: ['U', 'R'] },
        { name: 'Hissing Quagmire', color_identity: ['B', 'G'] },
        { name: 'Needle Spires', color_identity: ['R', 'W'] },
        { name: 'Lumbering Falls', color_identity: ['G', 'U'] },
      ],
    },
    {
      name: 'Storage Lands',
      behavior: { etb_tapped: true, logic: 'storage_counters' },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [
        { cost: '{T}, Remove storage counter(s)', produces: '[Color A] per counter removed' },
      ],
      lands: [
        { name: 'Calciform Pools', color_identity: ['W', 'U'] },
        { name: 'Dreadship Reef', color_identity: ['U', 'B'] },
        { name: 'Molten Slagheap', color_identity: ['B', 'R'] },
        { name: 'Fungal Reaches', color_identity: ['R', 'G'] },
        { name: 'Saltcrusted Steppe', color_identity: ['G', 'W'] },
      ],
    },
    {
      name: 'Odyssey Filter Lands',
      behavior: { etb_tapped: false, logic: 'filter_mana_1_generic' },
      sim_flags: { entersTappedAlways: false, isOdysseyFilter: true },
      mana_abilities: [
        { mode: 1, cost: '{T}', produces: '{C}' },
        { mode: 2, cost: '{1}, {T}', produces: 'Choice of {A}{A}, {A}{B}, or {B}{B}' },
      ],
      lands: [
        { name: 'Darkwater Catacombs', color_identity: ['U', 'B'] },
        { name: 'Shadowblood Ridge', color_identity: ['B', 'R'] },
        { name: 'Mossfire Valley', color_identity: ['R', 'G'] },
        { name: 'Skycloud Expanse', color_identity: ['W', 'U'] },
        { name: 'Sungrass Prairie', color_identity: ['G', 'W'] },
      ],
    },
    {
      name: 'Fallout Filter Lands',
      behavior: { etb_tapped: false, logic: 'filter_mana_1_generic' },
      sim_flags: { entersTappedAlways: false, isOdysseyFilter: true },
      mana_abilities: [
        { mode: 1, cost: '{T}', produces: '{C}' },
        { mode: 2, cost: '{1}, {T}', produces: 'Choice of {A}{A}, {A}{B}, or {B}{B}' },
      ],
      lands: [
        { name: 'Desolate Mire', color_identity: ['U', 'B'] },
        { name: 'Ferrous Lake', color_identity: ['B', 'R'] },
        { name: 'Viridescent Bog', color_identity: ['R', 'G'] },
        { name: 'Sunscorched Divide', color_identity: ['W', 'U'] },
        { name: 'Overflowing Basin', color_identity: ['G', 'W'] },
      ],
    },
    {
      name: 'Extra Bounce Lands',
      behavior: { etb_tapped: true, logic: 'return_land_on_etb' },
      sim_flags: { entersTappedAlways: true, isBounce: true },
      mana_abilities: [{ cost: '{T}', produces: '[Color]' }],
      lands: [
        { name: 'Coral Atoll', color_identity: ['U'] },
        { name: 'Dormant Volcano', color_identity: ['R'] },
        { name: 'Jungle Basin', color_identity: ['G'] },
        { name: 'Karoo', color_identity: ['W'] },
        { name: 'Slippery Karst', color_identity: ['G'] },
        { name: 'Smoldering Crater', color_identity: ['R'] },
        { name: 'Polluted Mire', color_identity: ['B'] },
        { name: 'Remote Isle', color_identity: ['U'] },
        { name: 'Drifting Meadow', color_identity: ['W'] },
      ],
    },
    {
      name: 'Various Utility Tap Lands',
      behavior: { etb_tapped: true },
      sim_flags: { entersTappedAlways: true },
      mana_abilities: [{ cost: '{T}', produces: 'Any color' }],
      lands: [
        { name: 'Path of Ancestry', color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: 'Rupture Spire', color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: 'Transguild Promenade', color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: 'Gond Gate', color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: "Baldur's Gate", color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: 'Crystal Grotto', color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: 'Painted Bluffs', color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: 'Shimmerdrift Vale', color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: "Survivor's Encampment", color_identity: ['W', 'U', 'B', 'R', 'G'] },
        { name: 'Holdout Settlement', color_identity: ['W', 'U', 'B', 'R', 'G'] },
      ],
    },
    {
      name: 'Special Lands',
      behavior: { etb_tapped: false, logic: 'double_colorless_with_drawback' },
      sim_flags: { isSpecialLand: true, manaAmount: 2, entersTappedAlways: false },
      mana_abilities: [{ cost: '{T}', produces: '{C}{C}', note: 'drawback varies per land' }],
      lands: [
        {
          name: 'Ancient Tomb',
          color_identity: [],
          sim_flags: { lifeloss: 2 },
          drawback: 'deals_2_damage_to_controller',
        },
        { name: 'City of Traitors', color_identity: [], drawback: 'sacrifice_when_land_played' },
      ],
    },
  ],
};

export default LANDS_DATA;
